version: "3.3"
services:

  backend:
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
    build:
      context: ./backend
      dockerfile: python3.9-slim.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
      - "${DOCKER_IMAGE_BACKEND_PORT}:80"

  frontend:
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
    build:
      context: ./frontend
      dockerfile: python3.9-slim.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
      - "${DOCKER_IMAGE_FRONTEND_PORT}:80"

volumes:
  app-db-data:
