version: "3.7"
# created with cookiecutter for project '{{ cookiecutter.project_name }}'
services:
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm.json
      - KEYCLOAK_LOGLEVEL=INFO
    volumes:
      - ./spot/tests/realm.json:/tmp/realm.json
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    depends_on:
      - keycloak
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--log-format=json"
      - "/policy/test.rego"
    volumes:
      - ./spot/tests/policy:/policy
  spot:
    image: '${DOCKER_IMAGE_SPOT?Variable not set}:${TAG-latest}'
    env_file:
      - .env
    environment:
      - SERVER_NAME=spot
      - SERVER_HOST=http://spot:${DOCKER_IMAGE_SPOT_PORT}
      - LOG_LEVEL=debug
      # Allow explicit env var override for tests
    depends_on:
      - opa
    build:
      context: ./spot
      dockerfile: python3.9-slim.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
      - "${DOCKER_IMAGE_SPOT_PORT}:${DOCKER_IMAGE_SPOT_PORT}"

#volumes:
#  app-db-data:
