name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install -r dev_requirements.txt
      - name: Run tests
        run: |
          sudo ./scripts/test.sh
