name: PyLint Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  gitHubActionForPylint:
    runs-on: ubuntu-latest
    env:
      working-directory: \{\{cookiecutter.project_slug\}\}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.8
      - name: Install dependencies
        run: |
          echo "upgrade pip"
          python -m pip install --upgrade pip
          echo "install requirements_dev.txt"
          pip install -r requirements_dev.txt
          echo "install pylint pylint-exit"
          pip install pylint pylint-exit
      - name: Run pylint
        run: |
          echo "pwd"
          pwd
          echo "ls -la"
          ls -la
          echo "cd \{\{cookiecutter.project_slug\}\}"
          cd \{\{cookiecutter.project_slug\}\}
          echo "start pylint"
          pylint --rcfile=.pylintrc **/*.py | pylint-exit $?
